
function selected = start_menu()

    % Inizializza il valore di default
    selected = '';

    % Crea la figura
    mainFig = figure('Name', 'SWAPS software', ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.3, 0.4, 0.3], ...
        'Color', [1 1 1], ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'NumberTitle', 'off', ...
        'CloseRequestFcn', @(src, event) chiudi_figura(src));

    % Opzioni reali
    opt = {' ......  ', 'Start Analysis with SWAPS', 'Create synthetic file and plot curves'};

    % Popup menu
    popup = uicontrol(mainFig, ...
        'Style', 'popupmenu', ...
        'String', opt, ...
        'Units', 'normalized', ...
        'Position', [0.02 0.92 0.4 0.06], ...
        'FontSize', 11, ...
        'BackgroundColor', [1 1 1], ...
        'Callback', @(src, event) popup_callback(src, mainFig));

    % Scritta "SWAPS" al centro
    annotation(mainFig, 'textbox', ...
        [0 0 1 1], ...
        'String', ' SWAPS ', ...
        'FontSize', 70, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'EdgeColor', 'none', ...
        'Color', [0.65 0.65 0.65]);


    % Blocca esecuzione finché l'utente non sceglie o chiude
    uiwait(mainFig);

    % Recupera la selezione, se esiste
    if isvalid(mainFig) && isappdata(mainFig, 'selected_option')
        selected = getappdata(mainFig, 'selected_option');
        delete(mainFig);
    end
end

function popup_callback(src, fig)
    % Se è selezionato il placeholder, non fare nulla
    if src.Value == 1
        return;
    end

    % Salva la selezione nella figura
    setappdata(fig, 'selected_option', src.String{src.Value});
    uiresume(fig);  % Sblocca uiwait
end

function chiudi_figura(fig)
    uiresume(fig);  % Sblocca uiwait (senza crash)
    delete(fig);    % Chiude la finestra
end
